modLoader="javafml"
loaderVersion="[39,)"
license="All rights reserved"

[[mods]]
modId="heftycrops"
version="1.0"
displayName="Hefty Crops"
logoFile="logo.png"
authors="crispytwig"
description='''
Crops but HEFTY!
'''

[[dependencies.heftycrops]]
    modId="forge"
    mandatory=true
    versionRange="[39,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.heftycrops]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.1,1.18.2)"
    ordering="NONE"
    side="BOTH"

[[dependencies.heftycrops]]
    modId = "farmersdelight"
    mandatory = false
    versionRange = "[1.0.3,)"
    ordering = "NONE"
    side = "BOTH"

