modLoader="javafml"
loaderVersion="[40,)"
license="All rights reserved"

[[mods]]
modId="heftycrops"
version="1.18.2-1.1"
displayName="Hefty Crops"
logoFile="logo.png"
authors="crispytwig, SameButDifferent"
description='''
Hefty Crops is a lightweight farming mod with the goal of adding slight variation to Vanilla farming.'''

[[dependencies.heftycrops]]
    modId="forge"
    mandatory=true
    versionRange="[40,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.heftycrops]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2,1.19)"
    ordering="NONE"
    side="BOTH"

[[dependencies.heftycrops]]
    modId = "farmersdelight"
    mandatory = false
    versionRange = "[1.0.4,)"
    ordering = "NONE"
    side = "BOTH"

