modLoader="javafml"
loaderVersion="[40,)"
license="All rights reserved"

[[mods]]
modId="heftycrops"
version="1.0.0"
displayName="Hefty Crops"
logoFile="logo.png"
authors="crispytwig"
description='''
Crops but HEFTY!
'''

[[dependencies.heftycrops]]
    modId="forge"
    mandatory=true
    versionRange="[40,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.heftycrops]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2,1.19)"
    ordering="NONE"
    side="BOTH"
